2013/08/07 07:23:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2
HTTP_REFERER=http://localhost/index.php?r=gii/controller
---
2013/08/07 07:23:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:23:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:24:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:24:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:24:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:24:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:24:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:24:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:24:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:24:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:24:11 [error] [php] include(OAuth.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\oauthserver\protected\controllers\Oauth2Controller.php(7): spl_autoload_call()
#1 D:\srv\www\framework\web\actions\CInlineAction.php(49): Oauth2Controller->actionToken()
#2 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 D:\srv\www\framework\web\CController.php(286): Oauth2Controller->runAction()
#4 D:\srv\www\framework\web\CController.php(265): Oauth2Controller->runActionWithFilters()
#5 D:\srv\www\framework\web\CWebApplication.php(282): Oauth2Controller->run()
#6 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 D:\srv\www\oauthserver\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=oauth2/token
in D:\srv\www\oauthserver\protected\controllers\Oauth2Controller.php (7)
in D:\srv\www\oauthserver\index.php (13)
2013/08/07 07:31:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:33:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:33:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:33:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:33:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:33:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:33:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/oauth2/
---
2013/08/07 07:34:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/oauth2
---
2013/08/07 07:35:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:35:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:35:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:35:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:35:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:35:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:35:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:35:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:35:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:37:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:37:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:37:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:37:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:37:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:37:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:44:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:44:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:44:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:49:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:49:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:49:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:49:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:52:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:54:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:54:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:54:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:54:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:54:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:54:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:54:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:54:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:54:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:55:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:55:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:55:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:55:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:55:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:55:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:58:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:58:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:58:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:58:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:00:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "authorize.php".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('authorize.php')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('authorize.php')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/oauth2/authorize.php?response_type=code&client_id=testclient&state=xyz
---
2013/08/07 08:00:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:00:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:00:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:01:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:01:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:01:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:02:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:02:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:02:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:02:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:02:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:02:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:02:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:02:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:04:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:04:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:05:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:05:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:05:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:05:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:06:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:07:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:07:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:07:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:09:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:09:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:09:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:09:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:09:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:09:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:31:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 09:15:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2
---
2013/08/07 09:15:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "authrozix".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('authrozix')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('authrozix')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authrozi...')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authrozix
---
2013/08/07 19:05:05 [error] [exception.PDOException] exception 'PDOException' with message 'SQLSTATE[HY000] [1049] Unknown database 'oauth2'' in D:\srv\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth2\Storage\Pdo.php:41
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth2\Storage\Pdo.php(41): PDO->__construct('mysql:dbname=oa...', 'root', '')
#1 D:\srv\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth.php(23): OAuth2\Storage\Pdo->__construct(Array)
#2 D:\srv\www\OAuth2-for-Yii\protected\controllers\Oauth2Controller.php(8): OAuth->__construct(Array)
#3 D:\srv\www\framework\web\CWebApplication.php(281): Oauth2Controller->init()
#4 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#5 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#6 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/07 19:05:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/07 21:34:25 [error] [exception.InvalidArgumentException] exception 'InvalidArgumentException' with message 'Argument "is_authorized" must be a boolean.  This method must know if the user has granted access to the client.' in D:\srv\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth2\Controller\AuthorizeController.php:64
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth2\Server.php(232): OAuth2\Controller\AuthorizeController->handleAuthorizeRequest(Object(OAuth2\Request), Object(OAuth2\Response), NULL, NULL)
#1 D:\srv\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth.php(72): OAuth2\Server->handleAuthorizeRequest(Object(OAuth2\Request), Object(OAuth2\Response), NULL)
#2 D:\srv\www\OAuth2-for-Yii\protected\controllers\Oauth2Controller.php(17): OAuth->authorize()
#3 D:\srv\www\framework\web\actions\CInlineAction.php(49): Oauth2Controller->actionAuthorize()
#4 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('authorize')
#8 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#9 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize?response_type=code&client_id=testclient&state=xyz
---
2013/08/07 21:35:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/07 21:35:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/07 22:01:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "taken".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('taken')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('taken')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/taken')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/taken?grant_type=authorization_code&code=1083928674bc118b3b44a0588832447bbdf2fcba
---
2013/08/08 05:18:56 [error] [php] Undefined variable: supportedScopes (D:\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth.php:26)
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize?client_id=testclient&redirect_uri=http%3A%2F%2Flocalhost%2Fphp-openid-connect-client-master%2Fpublic%2Findex.php&response_type=code&scope=basic&state=4ac8a64444076b5a4300fcb659173217bb543f89141fbea59ca5e916d5445178
in D:\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth.php (26)
in D:\www\OAuth2-for-Yii\protected\controllers\Oauth2Controller.php (8)
in D:\www\OAuth2-for-Yii\index.php (13)
2013/08/08 05:19:11 [error] [php] Undefined variable: server (D:\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth.php:29)
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize?client_id=testclient&redirect_uri=http%3A%2F%2Flocalhost%2Fphp-openid-connect-client-master%2Fpublic%2Findex.php&response_type=code&scope=basic&state=4ac8a64444076b5a4300fcb659173217bb543f89141fbea59ca5e916d5445178
in D:\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth.php (29)
in D:\www\OAuth2-for-Yii\protected\controllers\Oauth2Controller.php (8)
in D:\www\OAuth2-for-Yii\index.php (13)
2013/08/08 08:22:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth
---
2013/08/08 08:22:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\www\framework\web\CController.php:483
Stack trace:
#0 D:\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2
---
2013/08/08 08:22:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\www\framework\web\CController.php:483
Stack trace:
#0 D:\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2
---
2013/08/08 08:22:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\www\framework\web\CController.php:483
Stack trace:
#0 D:\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/08 08:22:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\www\framework\web\CController.php:483
Stack trace:
#0 D:\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/08 08:23:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "register".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('register')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/register
---
2013/08/08 08:46:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:46:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:46:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:46:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:46:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:46:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:46:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:46:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:46:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:46:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:51:04 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:32 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:42 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:42 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:43 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:43 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:43 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:43 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:43 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:43 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:44 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 09:01:05 [error] [exception.CException] exception 'CException' with message 'TokenController and its behaviors do not have a method or closure named "setOauth".' in D:\www\framework\base\CComponent.php:265
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__call('setOauth', Array)
#1 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): TokenController->setOauth(Object(OAuth))
#2 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(TokenController), Object(CInlineAction))
#3 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#4 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#5 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#6 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/token
HTTP_REFERER=http://localhost/OAuth2-for-Yii/index.php/gii/controller
---
2013/08/08 09:01:30 [error] [php] Undefined property: OAuth::$token (D:\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\TokenController.php:8)
Stack trace:
#0 D:\www\framework\web\CController.php(286): TokenController->runAction()
#1 D:\www\framework\web\CController.php(265): TokenController->runActionWithFilters()
#2 D:\www\framework\web\CWebApplication.php(282): TokenController->run()
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/token
in D:\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\TokenController.php (8)
in D:\www\OAuth2-for-Yii\index.php (13)
2013/08/08 09:18:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/
---
2013/08/09 03:02:56 [error] [exception.CException] exception 'CException' with message 'OauthController and its behaviors do not have a method or closure named "setOauth".' in D:\www\framework\base\CComponent.php:265
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__call('setOauth', Array)
#1 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): OauthController->setOauth(Object(OAuth))
#2 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(OauthController), Object(CInlineAction))
#3 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#4 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/oauth')
#5 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#6 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/oauth
HTTP_REFERER=http://localhost/OAuth2-for-Yii/index.php/gii/controller
---
2013/08/09 03:16:15 [error] [php] Undefined property: OAuth::$oauth (D:\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php:8)
Stack trace:
#0 D:\www\framework\web\CController.php(286): AuthorizeController->runAction()
#1 D:\www\framework\web\CController.php(265): AuthorizeController->runActionWithFilters()
#2 D:\www\framework\web\CWebApplication.php(282): AuthorizeController->run()
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize
in D:\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php (8)
in D:\www\OAuth2-for-Yii\index.php (13)
2013/08/09 04:35:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 09:23:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 09:24:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 09:24:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 09:24:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 10:44:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 10:45:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 10:45:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 10:45:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 10:45:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 10:45:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 10:46:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token/default/l...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/default/login
---
2013/08/09 10:52:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token/default/l...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/default/login
---
2013/08/09 10:52:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/
---
2013/08/09 10:52:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/
---
2013/08/09 10:52:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/
---
2013/08/09 10:52:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/
---
2013/08/09 10:52:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/
---
2013/08/09 10:52:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/
---
2013/08/09 10:52:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/
---
2013/08/09 10:52:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token
---
2013/08/09 10:52:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token
---
2013/08/09 10:52:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token
---
2013/08/09 10:52:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token
---
2013/08/09 10:52:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token
---
2013/08/09 10:52:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token
---
2013/08/09 10:52:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token
---
2013/08/09 10:52:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token
---
2013/08/09 10:52:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize
---
2013/08/09 10:53:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token/login')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/login
---
2013/08/09 21:16:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/login".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/login')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/login
HTTP_REFERER=http://localhost/client/
---
2013/08/09 21:26:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oatuh2/authorize
---
2013/08/09 21:26:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:26:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:26:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:26:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:26:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:26:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:26:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:26:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:27:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:27:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:27:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:27:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:27:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:27:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:27:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize
---
2013/08/09 21:28:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "authorize".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize
---
